# fly.toml file generated for laravel-fly on 2022-11-11T16:12:59+09:00

app = "laravel-fly"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "7.4"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  APP_KEY = "base64:fOm69HRarI2S3XKpHrKE9JJzgBcnPCL/8tvsT4Oj3oo="
  APP_DEBUG = true
  DB_HOST = "laravel-postgres.internal"
  DB_DATABASE = "laravel-postgres"
  DB_USERNAME = "postgres"
  DB_PASSWORD = "OEeD0JCBPKDWIw9"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
